export const CHAT_REPOSITORY = Symbol('CHAT_REPOSITORY');
export const DISCUSSION_REPOSITORY = Symbol('DISCUSSION_REPOSITORY');
export const SOURCE_REPOSITORY = Symbol('SOURCE_REPOSITORY');
export const LLM_QUESTION_ANSWERING = Symbol('LLM_QUESTION_ANSWERING');
export const EVALUATION_REPOSITORY = Symbol('EVALUATION_REPOSITORY');
export const S3_REPOSITORY = Symbol('S3_REPOSITORY');
