networks:
  app-network:
    driver: bridge


services:
  postgres:
    image: postgres:16.2-alpine
    expose:
      - 5432
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - app-network

volumes:
  app-postgres:
    driver: local